version = 0.1

[default.deploy.parameters]
stack_name = "ai-locus-agent"
resolve_s3 = true
s3_prefix = "ai-locus-agent"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
